'use strict';
async function openEditorTools(entry,clip){
 const d=el('dialog','editor-tools-dialog');d.innerHTML='<header class="library-dialog-head"><div><small>剪辑片段 · 本机处理</small><h2>声音与画面工具</h2></div><button class="secondary close-tools">关闭</button></header><p class="tools-source"></p><div class="tools-form"><label>处理功能<select name="operation"></select></label><p class="tools-description"></p><label data-field="reference">参考／驱动音频<select name="referenceAssetId"></select></label><label data-field="referenceText">参考录音原话<textarea name="referenceText" rows="2"></textarea></label><label data-field="text">新台词<textarea name="text" rows="3"></textarea></label><label data-field="sourceText">片段中的准确台词<textarea name="sourceText" rows="2"></textarea></label><label data-field="instruction">局部修改说明<textarea name="instruction" rows="2" placeholder="例如：把“今天”替换为“明天”，保留其他台词"></textarea></label><label>运行设备<select name="device"></select></label><button class="primary tools-run">处理所选片段</button><p class="tools-status" role="status"></p><div class="tools-results"></div></div>';
 document.body.append(d);d.showModal();d.querySelector('.close-tools').onclick=()=>d.close();let poll=null,closed=false,polling=false;d.addEventListener('close',()=>{closed=true;clearInterval(poll);d.querySelectorAll('audio,video').forEach(m=>m.pause());d.remove();});d.querySelector('.tools-source').textContent=`${clip.clipName||'所选片段'} · 素材入点 ${clip.in.toFixed(2)} 秒 · 时长 ${clip.duration.toFixed(2)} 秒`;
 const status=d.querySelector('.tools-status'),run=d.querySelector('.tools-run'),operation=d.querySelector('[name=operation]'),device=d.querySelector('[name=device]');run.disabled=true;
 const descriptions={extract_audio:'FFmpeg：提取所选裁切范围的原声。',separate_vocals:'Demucs：把选中片段拆成人声与其余声音。',transcribe:'faster-whisper：识别选中片段的对白，核对后放回原时间位置。',tts:'Qwen3-TTS：以选中片段的单人原声为音色参考，朗读新台词。',voice_convert:'Seed-VC：保留选中片段的台词和表演，转换为参考音色。',speech_edit:'dots.tts.edit：按准确原话与指令生成声音精修候选。',lip_sync:'MuseTalk：使用选中视频与驱动对白，生成口型候选。'};
 const labels={extract_audio:'提取原声 · FFmpeg',separate_vocals:'分离人声 · Demucs',transcribe:'识别片段字幕 · Whisper',tts:'参考声线配音 · Qwen3-TTS',voice_convert:'保留表演换声 · Seed-VC',speech_edit:'局部配音精修 · dots.tts.edit',lip_sync:'口型修复 · MuseTalk'};
 let caps;
 try{const [tools,media]=await Promise.all([entry.request('/api/local-capabilities'),entry.request('/api/media')]);caps=tools;for(const [op,label] of Object.entries(labels)){const available=op==='extract_audio'?tools.ffmpeg:op==='separate_vocals'?tools.demucsModelReady:tools.models.find(m=>m.operation===op)?.ready;const option=new Option(label+(available?'':' · 未就绪'),op);option.disabled=!available||(op==='lip_sync'&&clip.kind!=='video');operation.append(option);}operation.value=[...operation.options].find(o=>!o.disabled)?.value||'';const references=d.querySelector('[name=referenceAssetId]');references.append(new Option('选择当前项目的音频',''));media.assets.filter(a=>a.mediaType==='audio').forEach(a=>references.append(new Option(a.name,a.id)));run.disabled=!operation.value;}catch(e){status.textContent=e.message;return;}
 function update(){const op=operation.value;for(const [key,visible] of Object.entries({reference:['voice_convert','lip_sync'].includes(op),referenceText:op==='tts',text:op==='tts',sourceText:op==='speech_edit',instruction:op==='speech_edit'}))d.querySelector('[data-field='+key+']').hidden=!visible;d.querySelector('.tools-description').textContent=descriptions[op]+' 使用素材裁切范围，不烘焙时间线音效；结果不会覆盖原素材。';device.replaceChildren();const engine=caps.models.find(m=>m.operation===op);if(['transcribe','tts','extract_audio'].includes(op))device.append(new Option('CPU','cpu'));if(caps.cuda&&op!=='extract_audio')device.append(new Option('NVIDIA 显卡','cuda'));if(!device.options.length)device.append(new Option('CPU','cpu'));device.value=engine?.device==='cuda'&&caps.cuda?'cuda':device.options[0].value;}
 operation.onchange=update;update();
 async function finished(job){clearInterval(poll);status.textContent='处理完成。先试听／试看，再决定是否加入剪辑。';const results=d.querySelector('.tools-results');
  for(const a of job.assets||[]){const row=el('section','editor-tool-result'),title=el('strong','',a.name),preview=el(a.mediaType==='video'?'video':'audio');preview.src=safeUrl(a.mediaUrl);preview.controls=true;preview.preload='metadata';const actions=el('div','dialog-actions');
   const add=async place=>{await entry.send('flush');await entry.request('/api/editor/import-assets',{assetIds:[a.id]});await entry.send('sync');if(place)await entry.send('place-result',{assetId:a.id,context:job.editorClip,muteOriginal:row.querySelector('input').checked});toast(place?'已添加到原片段位置':'已加入素材箱');};
   const mute=el('label','tools-mute'),check=el('input');check.type='checkbox';check.checked=true;mute.append(check,document.createTextNode('放入新轨道时静音原片段及关联原声'));
   actions.append(button('加入素材箱','secondary',()=>add(false).catch(e=>toast(e.message,true))),button('放入新轨道','primary',()=>add(true).catch(e=>toast(e.message,true))));row.append(title,preview,mute,actions);results.append(row);
  }
  if(job.transcript){const text=el('textarea');text.readOnly=true;text.rows=4;text.value=job.transcript.text||job.transcript.segments.map(s=>s.text).join('');const apply=button('将字幕放回原片段位置','primary',async()=>{try{await entry.send('flush');const doc=await entry.request('/api/editor/project');const original=doc.clips.find(c=>c.id===job.editorClip.id);if(!original||['mediaId','start','in','duration'].some(k=>original[k]!==job.editorClip[k]))throw new Error('原片段已改变，请在时间线重新识别字幕');await entry.request('/api/editor/captions/apply',{jobId:job.id,revision:doc.revision,position:'bottom',offset:job.editorClip.start,replaceAuto:false,replaceClipAuto:true});await entry.send('sync');toast('字幕已放回原时间位置');}catch(e){toast(e.message,true);}});results.append(text,apply);}
 }
 let requestKey='',stableRequestId='';
 run.onclick=async()=>{run.disabled=true;operation.disabled=true;status.textContent='正在截取片段并创建本机任务…';try{await entry.send('flush');const doc=await entry.request('/api/editor/project');const current=doc.clips.find(c=>c.id===clip.clipId);if(!current||['mediaId','start','in','duration'].some(k=>current[k]!==clip[k]))throw new Error('片段已变化，请关闭工具卡后重新选择');const body={clipId:clip.clipId,revision:doc.revision,operation:operation.value,requestId:'editor-'+crypto.randomUUID(),device:device.value};for(const key of ['referenceAssetId','referenceText','text','sourceText','instruction'])body[key]=d.querySelector('[name='+key+']').value;const key=JSON.stringify({...body,requestId:undefined,revision:undefined});if(key!==requestKey){requestKey=key;stableRequestId=body.requestId;}body.requestId=stableRequestId;const job=await entry.request('/api/editor/process',body);status.textContent='任务已创建；关闭此卡片后可在顶部“任务”继续查看。';poll=setInterval(async()=>{if(polling||closed)return;polling=true;try{const list=await entry.request('/api/local-jobs'),j=list.jobs.find(x=>x.id===job.id);if(j?.status==='succeeded')await finished(j);else if(j?.status==='failed'){clearInterval(poll);status.textContent=j.error;run.disabled=false;operation.disabled=false;}else status.textContent=j?.stage||'本机任务排队中…';}catch(e){status.textContent=e.message;}finally{polling=false;}},1600);}catch(e){status.textContent=e.message;run.disabled=false;operation.disabled=false;}};
}
