/* 镜序 · production graph. All generation remains an explicit Codex task. */
'use strict';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const state = {graph:null,assets:[],production:{shots:[],summary:{}},project:null,models:{image:[],video:[]},jobs:[],validation:new Map(),scene:'',shot:new URLSearchParams(location.search).get('shot') || '',selected:null,selectedAsset:null,selectedEdge:null,visible:[],dirty:false,saving:false,mutation:0,queueTab:'pending',compiled:null,transform:{x:30,y:35,scale:.7},drag:null,connecting:null,busy:false};
state.viewPositions=new Map();state.layoutKey=null;state.preparedRun=null;state.uncertainRun=null;
const positionFor=n=>state.viewPositions.get(n.id)||n.position;
function compactScope(){const key=`${state.scene}/${state.shot}`;if(state.layoutKey===key)return;state.layoutKey=key;state.viewPositions.clear();if(!state.scene&&!state.shot||!state.visible.length)return;const xs=state.visible.map(n=>positionFor(n).x),ys=state.visible.map(n=>positionFor(n).y);const height=n=>n.type==='video'?430:['asset','image'].includes(n.type)?340:310;const collision=state.visible.some((a,i)=>state.visible.slice(i+1).some(b=>a.position.x<b.position.x+330&&a.position.x+330>b.position.x&&a.position.y<b.position.y+height(b)&&a.position.y+height(a)>b.position.y));if(!collision&&Math.max(...xs)-Math.min(...xs)<3500&&Math.max(...ys)-Math.min(...ys)<(state.shot?850:2500))return;const ids=new Set(state.visible.map(n=>n.id)),levels=new Map(),visits=new Set();function level(id){if(levels.has(id))return levels.get(id);if(visits.has(id))return 0;visits.add(id);const parents=state.graph.edges.filter(e=>e.target===id&&ids.has(e.source));const l=parents.length?Math.max(...parents.map(e=>level(e.source)))+1:0;visits.delete(id);levels.set(id,l);return l;}const columns=new Map();state.visible.forEach(n=>{const l=level(n.id);if(!columns.has(l))columns.set(l,[]);columns.get(l).push(n);});let columnX=0;const maxRows=state.shot?2:5;[...columns.entries()].sort((a,b)=>a[0]-b[0]).forEach(([,nodes])=>{nodes.forEach((n,i)=>state.viewPositions.set(n.id,{x:columnX+Math.floor(i/maxRows)*370,y:(i%maxRows)*435}));columnX+=Math.ceil(nodes.length/maxRows)*370+35;});}
function materializeLayout(){if(!state.viewPositions.size)return;state.viewPositions.forEach((p,id)=>{const n=nodeBy(id);if(n)n.position={...p};});state.viewPositions.clear();}
const types = {asset:{name:'资源资产',icon:'▧',desc:'角色、场景、道具与素材',out:['image']},prompt:{name:'提示词',icon:'≡',desc:'画面、动作与镜头语言',in:['context'],out:['text']},image:{name:'分镜图像',icon:'▣',desc:'Design 或 Codex 图像待办',in:['prompt','references'],out:['image']},video:{name:'动态视频',icon:'▶',desc:'从分镜与参考资产生成动态素材',in:['prompt','references','firstFrame','audioReferences','videoReferences'],out:['video']},review:{name:'素材审核',icon:'✓',desc:'内容审阅与批准记录',in:['media'],out:['out']},reuse:{name:'复用素材',icon:'↗',desc:'引用已有批准素材，不重复生成',in:['source','audioPlan'],out:['video']},edit:{name:'后期剪辑',icon:'✂',desc:'裁切、声音与字幕制作待办',in:['source','text','audioPlan'],out:['video']},script:{name:'剧本',icon:'≡',desc:'剧本与风格来源',out:['text']}};
const portLabels={audioPlan:'声音计划',audioReferences:'声音参考',videoReferences:'视频参考',context:'上下文',audio:'音频',image:'图像',text:'提示文本',video:'视频',out:'审核输出',prompt:'提示词',references:'参考图',firstFrame:'首帧图',media:'待审素材',source:'源素材'};
const statuses={ready:'已就绪',blocked:'缺少依赖',external:'交给 Codex',waiting:'待准备',complete:'已有结果',candidate:'候选 · 待审核',missing:'文件缺失',draft:'待准备',succeeded:'已完成',success:'已完成',completed:'已完成',queued:'排队中',running:'生成中',submitted:'已提交',failed:'失败',unknown:'待查询',approved:'已批准',rejected:'退回',pending:'待处理'};
const kindLabels={text:'文字规格',prop_spec:'道具规范',costume:'服装状态',environment:'环境空间',character:'角色',scene:'场景',prop:'道具',storyboard:'分镜',image:'图像',video:'视频',audio:'声音',reference:'参考',identity:'身份',first_frame:'首帧',result:'结果'};
function assetReviewLabel(a){return a?.mediaType==='audio'&&a?.role==='voice_identity'&&a?.reviewStatus==='candidate'?'待选音 · 试听':statuses[a?.reviewStatus]||a?.reviewStatus||'待审核';}
function nodeStatusLabel(n,status){if(n.type==='video'&&status==='ready')return'画面可生成';if(n.type==='image'&&status==='ready')return'图像可生成';if(n.type==='asset'){const a=assetBy(n.assetId);if(a?.mediaType==='audio'&&a.role==='voice_identity'&&a.reviewStatus==='candidate')return'待选音 · 试听';}return statuses[status]||status;}
function portsFor(n,direction){if(direction==='output'&&n.type==='asset'){const a=assetBy(n.assetId),kind=a?.mediaType||a?.kind;return[['video','audio','text'].includes(kind)?kind:'image'];}return types[n.type]?.[direction==='input'?'in':'out']||[];}
const el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
const uid=()=>crypto.randomUUID();
const textPreviewCache=new Map();
function showAudioPreview(media,box){box.classList.add('audio-preview');const asset=media.asset||{};box.append(el('div','audio-name',asset.name||'音频素材'));if(Array.isArray(asset.waveform)&&asset.waveform.length){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 280 62');svg.classList.add('audio-waveform');const samples=asset.waveform.slice(0,100),max=Math.max(...samples.map(Math.abs),.001);samples.forEach((v,i)=>{const line=document.createElementNS(svg.namespaceURI,'line');const amplitude=Math.max(1,Math.abs(Number(v)||0)/max*28),x=2+i*276/Math.max(samples.length-1,1);line.setAttribute('x1',x);line.setAttribute('x2',x);line.setAttribute('y1',31-amplitude);line.setAttribute('y2',31+amplitude);svg.append(line);});box.append(svg);}else box.append(el('p','field-help','试听原始音频'));if(media.url){const audio=el('audio');audio.src=media.url;audio.controls=true;audio.preload='metadata';box.append(audio);}else box.append(el('p','field-help','音频文件未就绪'));return box;}
function showTextPreview(media,box,inspector){box.classList.add('text-preview');const header=el('div','text-preview-label','≡ 文字规格 · 提示词上下文');const content=el('pre','text-preview-content',media.asset?.notes||'正在读取文字规格…');box.append(header,content);if(media.url){if(!textPreviewCache.has(media.url))textPreviewCache.set(media.url,fetch(media.url).then(r=>{if(!r.ok)throw new Error('读取失败');return r.text();}));textPreviewCache.get(media.url).then(text=>{content.textContent=inspector?text:text.slice(0,650);}).catch(()=>content.textContent=media.asset?.notes||'文字规格暂时无法读取');}return box;}
const nodeBy=id=>state.graph?.nodes.find(n=>n.id===id);
const assetBy=id=>state.assets.find(a=>a.id===id);
const shotBy=id=>state.production.shots.find(s=>(s.shotId||s.id)===id)||state.project?.shots.find(s=>s.id===id);
function toast(message,error=false){const e=$('#toast');e.textContent=message;e.classList.toggle('error',error);e.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.hidden=true,error?6500:3500);}
async function api(path,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);try{const r=await fetch(path,{...options,headers:{Accept:'application/json',...(state.workspaceId?{'X-Studio-Workspace':state.workspaceId}:{}),...(options.body?{'Content-Type':'application/json'}:{}),...(options.method&&options.method!=='GET'?{'X-Studio-Request':'1'}:{}),...options.headers},signal:controller.signal});const data=await r.json();if(!r.ok){const e=new Error(data.error||data.message||`请求失败 (${r.status})`);e.status=r.status;throw e;}return data;}catch(e){if(e.name==='AbortError')throw new Error('服务响应超时。请检查启动窗口或稍后重新连接；不要重复提交正在生成的任务。');if(e instanceof TypeError){window.dispatchEvent(new Event('studio:offline'));throw new Error('未连接到本地服务。请双击桌面“镜序 Studio”启动软件，再点击重新连接。');}throw e;}finally{clearTimeout(timer);}}
function safeUrl(url){try{const u=new URL(url,location.href);return url&&u.origin===location.origin&&/^https?:$/.test(u.protocol)?u.href:'';}catch{return '';}}
function markDirty(){state.dirty=true;state.mutation++;state.compiled=null;state.validation.clear();updateSave();$('#compiledCount').textContent='0';}
function updateSave(){$('#saveState').textContent=state.saving?'正在保存…':state.dirty?'有未保存的更改':'工作流已保存';$('#saveState').classList.toggle('dirty',state.dirty);$('#saveBtn').disabled=state.saving||!state.graph;$('#graphRevision').textContent=`修订 ${state.graph?.revision??'—'}`;}
async function saveGraph(notify=true){if(!state.graph||state.saving)return false;const invalid=document.querySelector("#inspectorBody input:invalid, #inspectorBody textarea:invalid");if(invalid){invalid.reportValidity();toast('请先修正节点参数',true);return false;}if(!state.dirty)return true;state.saving=true;updateSave();const version=state.mutation;try{const result=await api('/api/workflow',{method:'PUT',body:JSON.stringify(state.graph)});const graph=result.workflow||result;state.graph.revision=graph.revision;if(version===state.mutation){state.graph=graph;state.dirty=false;renderInspector();}$('#conflictBar').hidden=true;if(notify)toast('工作流已保存');return true;}catch(e){if(e.status===409)$('#conflictBar').hidden=false;toast(`保存失败：${e.message}`,true);return false;}finally{state.saving=false;updateSave();}}
function sceneGroups(){const groups=new Map();state.production.shots.forEach(s=>{const key=s.sceneId||s.scene||'未分类';if(!groups.has(key))groups.set(key,{id:key,name:s.scene||key,shots:[]});groups.get(key).shots.push(s);});return [...groups.values()];}
function setScope(scene,shot=''){state.scene=scene;state.shot=shot;state.selectedEdge=null;renderNavigation();renderGraph();renderQueue();requestAnimationFrame(fitCanvas);}
function renderNavigation(){const groups=sceneGroups();$('#totalShots').textContent=state.production.shots.length;$('#totalScenes').textContent=groups.length;$('#resourceCount').textContent=`${state.assets.length} 资产`;$('#allNodeCount').textContent=state.graph?.nodes.length||0;$('#allScenes').classList.toggle('active',!state.scene&&!state.shot);const list=$('#sceneList');list.replaceChildren();groups.forEach(group=>{const wrap=el('div',`scene-group${group.id===state.scene?' active':''}`),button=el('button','scene-button');button.append(el('span','scene-num',group.id),el('span','scene-name',group.name.replace(/^[^｜]*｜/,'')),el('span','scene-count',group.shots.length));button.title=group.name;button.onclick=()=>setScope(group.id);wrap.append(button);if(group.id===state.scene){const shots=el('div','shot-list');group.shots.forEach(s=>{const id=s.shotId||s.id;const b=el('button',`shot-button${state.shot===id?' active':''}`);b.append(el('b','',id),el('span','',s.title),el('i','',s.productionMode?.includes('复用')?'复用':`${s.plannedDuration||'—'}s`));b.onclick=()=>setScope(group.id,id);shots.append(b);});wrap.append(shots);}list.append(wrap);});const select=$('#shotFilter');select.replaceChildren();const all=el('option','',state.scene?'当前场全部镜头':'全片全部镜头');all.value='';select.append(all);(state.scene?groups.find(g=>g.id===state.scene)?.shots||[]:state.production.shots).forEach(s=>{const option=el('option','',`${s.shotId||s.id} · ${s.title}`);option.value=s.shotId||s.id;select.append(option);});select.value=state.shot;const shot=shotBy(state.shot),scene=groups.find(g=>g.id===state.scene);$('#scopeTitle').textContent=shot?`${state.shot} · ${shot.title}`:scene?`${scene.id} · ${scene.name.replace(/^[^｜]*｜/,'')}`:'全片工作流';}
function visibleNodes(){if(!state.graph)return[];if(!state.scene&&!state.shot)return state.graph.nodes;const shotIds=new Set(state.shot?[state.shot]:state.production.shots.filter(s=>(s.sceneId||s.scene)===state.scene).map(s=>s.shotId||s.id));const ids=new Set(state.graph.nodes.filter(n=>shotIds.has(n.shotId)||(n.data?.sceneId===state.scene&&!n.shotId)).map(n=>n.id));/* Follow upstream dependencies, never unrelated downstream consumers. */let changed=true;while(changed){changed=false;state.graph.edges.forEach(e=>{if(ids.has(e.target)&&!ids.has(e.source)){ids.add(e.source);changed=true;}});}return state.graph.nodes.filter(n=>ids.has(n.id));}
function nodeStatus(n){const v=state.validation.get(n.id);if(v)return v;const a=assetBy(n.assetId);if(n.type==='asset')return{status:a?(a.reviewStatus==='ready'?'ready':a.reviewStatus==='blocked'||a.reviewStatus==='missing'?'blocked':'waiting'):'blocked',missing:a?[]:['尚未指定资产']};if(n.data?.provider==='imagegen')return{status:'external',missing:[]};return{status:n.data?.status||'waiting',missing:[]};}
function mediaFor(n){const a=assetBy(n.assetId||n.data?.assetId);const job=state.jobs.find(j=>((j.workflowNodeId||j.nodeId)===n.id||(!j.workflowNodeId&&!j.nodeId&&j.shotId===n.shotId&&j.kind===n.type&&n.type==='video'))&&j.mediaUrl);return{url:safeUrl(a?.mediaUrl||n.data?.mediaUrl||job?.mediaUrl),thumb:safeUrl(a?.thumbnailUrl||n.data?.thumbnailUrl||job?.thumbnailUrl),kind:a?.mediaType||a?.kind||n.type,asset:a,job};}
function nodeText(n){return n.data?.text||n.data?.prompt||n.data?.notes||n.data?.instructions||(n.type==='reuse'?`复用 ${n.data?.reuseFrom||shotBy(n.shotId)?.reuseFrom||'上游批准素材'}，保留原始来源。`:n.type==='review'?'检查人物、动作、连续性与画面质量。技术完成后仍需内容审核。':n.type==='edit'?'后期制作待办：裁切、音轨与字幕合成。':'点击节点，设置资源与制作参数。');}
function createPreview(n,inspector=false){const media=mediaFor(n),box=el('div',inspector?'inspector-media':'node-preview');if(media.kind==='audio')return showAudioPreview(media,box);if(media.asset?.mediaType==='text'||media.kind==='text')return showTextPreview(media,box,inspector);const isVideo=/\.(mp4|webm|mov)(?:\?|$)/i.test(media.url)||media.kind==='video';if(media.url&&isVideo&&inspector){const v=el('video');v.src=media.url;v.controls=true;v.preload='metadata';if(media.thumb)v.poster=media.thumb;box.append(v);}else if(media.thumb||media.url&&!isVideo){const img=el('img');img.src=media.thumb||media.url;img.alt=media.asset?.name||n.label;img.loading='lazy';img.draggable=false;box.append(img);}else if(media.url&&isVideo){const v=el('video');v.src=media.url;v.preload='metadata';v.muted=true;box.append(v);}else{const empty=el('div','media-placeholder');empty.append(el('span','',types[n.type]?.icon||'▧'),el('div','',n.type==='asset'?'资源尚未就绪':n.type==='image'?'分镜图待生成':'动态素材待生成'));box.append(empty);}if(!inspector&&(media.url||media.thumb))box.append(el('span','preview-caption',media.asset?(assetReviewLabel(media.asset)||'参考资源'):media.job?.validationOnly?'验证试片 · 非正式成片':'已有素材 · 待内容验收'));return box;}
function buildNode(n){const type=types[n.type]||types.asset;const wrap=el('article',`graph-node${state.selected===n.id?' selected':''}${state.shot&&n.shotId&&n.shotId!==state.shot?' external':''}`);wrap.dataset.nodeId=n.id;wrap.dataset.type=n.type;wrap.style.left=`${positionFor(n).x}px`;wrap.style.top=`${positionFor(n).y}px`;wrap.tabIndex=0;wrap.setAttribute('aria-label',`${type.name}：${n.label}`);const head=el('div','node-head');head.append(el('span','node-symbol',type.icon),el('strong','',(n.type==='asset'?(n.data?.alias||assetBy(n.assetId)?.name):null)||n.label||type.name),el('small','',n.shotId||n.type.toUpperCase()));wrap.append(head);const a=assetBy(n.assetId);wrap.append(el('div','node-subtitle',n.type==='asset'?`${kindLabels[a?.kind]||a?.kind||'资产'} / ${kindLabels[n.data?.role||a?.role]||n.data?.role||a?.role||'参考'}${n.data?.usage==='post_mix'?' · 后期混音':''}`:n.data?.provider==='imagegen'?'CODEX · IMAGEGEN':n.type==='video'||n.type==='image'?n.data?.modelId||'模型待指定':type.desc));if(['asset','image','video'].includes(n.type))wrap.append(createPreview(n));else wrap.append(el('p','node-copy',window.Creator?.prettyPrompt?window.Creator.prettyPrompt(n,nodeText(n)):nodeText(n)));const status=nodeStatus(n);const statusEl=el('div',`node-status ${status.status}`);statusEl.append(el('span','',status.status==='ready'?'●':'◌'),el('span','',nodeStatusLabel(n,status.status)),el('span','',status.missing?.length?`${status.missing.length} 项缺失`:n.type==='reuse'?'不重复生成':n.type==='edit'?'后期待办':''));wrap.append(statusEl);const ports=el('div','ports');ports.style.height=`${Math.max(38,Math.max(portsFor(n,'input').length,portsFor(n,'output').length)*24+14)}px`;['input','output'].forEach(direction=>{const group=el('div',`port-group ${direction}`);portsFor(n,direction).forEach(port=>{const button=el('button','port');Object.assign(button.dataset,{nodeId:n.id,port,direction,label:portLabels[port]||port});button.title=`${direction==='input'?'输入':'输出'}：${portLabels[port]||port}`;button.setAttribute('aria-label',`${n.label} ${button.title}`);button.onpointerdown=e=>startConnection(e,n,port,direction);group.append(button);});ports.append(group);});wrap.append(ports);head.onpointerdown=e=>startNodeDrag(e,n,wrap);wrap.onclick=e=>{if(Date.now()-(state.lastDragAt||0)<250)return;if(!e.target.closest('.port,audio,video,button'))selectNode(n.id);};wrap.onkeydown=e=>{if(e.key==='Enter')selectNode(n.id);};return wrap;}
function renderGraph(){state.visible=visibleNodes();compactScope();const layer=$('#nodeLayer');layer.replaceChildren(...state.visible.map(buildNode));$('#canvasEmpty').hidden=!!state.visible.length;const ids=new Set(state.visible.map(n=>n.id));const edges=state.graph.edges.filter(e=>ids.has(e.source)&&ids.has(e.target));$('#scopeStats').textContent=`${state.visible.length} 节点 / ${edges.length} 连接${state.shot?' · 包含上游依赖':''}`;renderEdges();transformWorld();if(state.selected&&!state.visible.some(n=>n.id===state.selected)){state.selected=null;renderInspector();}}
function portPoint(nodeId,port,direction){const target=$$('.port').find(p=>p.dataset.nodeId===nodeId&&p.dataset.port===port&&p.dataset.direction===direction);if(!target)return null;const r=target.getBoundingClientRect();return localPoint({clientX:r.left+r.width/2,clientY:r.top+r.height/2});}
function bezier(a,b){const d=Math.max(65,Math.abs(b.x-a.x)*.48);return`M ${a.x} ${a.y} C ${a.x+d} ${a.y}, ${b.x-d} ${b.y}, ${b.x} ${b.y}`;}
function renderEdges(){const group=$('#edgePaths');group.replaceChildren();const ids=new Set(state.visible.map(n=>n.id));state.graph.edges.forEach(edge=>{if(!ids.has(edge.source)||!ids.has(edge.target))return;const a=portPoint(edge.source,edge.sourcePort||types[nodeBy(edge.source)?.type]?.out?.[0],'output'),b=portPoint(edge.target,edge.targetPort||types[nodeBy(edge.target)?.type]?.in?.[0],'input');if(!a||!b)return;const d=bezier(a,b);['edge','edge-hit'].forEach(cls=>{const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('class',`${cls}${state.selectedEdge===edge.id?' selected':''}`);p.dataset.edgeId=edge.id;p.addEventListener('pointerdown',e=>e.stopPropagation());p.onclick=e=>{e.stopPropagation();state.selectedEdge=edge.id;state.selected=null;state.selectedAsset=null;$$('.graph-node').forEach(n=>n.classList.remove('selected'));$('#selectedHint').textContent=`${nodeBy(edge.source)?.label} → ${nodeBy(edge.target)?.label}`;$('#deleteEdgeBtn').hidden=false;renderEdges();renderInspector();};group.append(p);});});}
function transformWorld(){const t=state.transform;$('#world').style.transform=`translate(${t.x}px,${t.y}px) scale(${t.scale})`;$('#zoomLabel').textContent=`${Math.round(t.scale*100)}%`;$('#viewport').style.backgroundSize=`${Math.max(18,26*t.scale)}px ${Math.max(18,26*t.scale)}px`;$('#viewport').style.backgroundPosition=`${t.x}px ${t.y}px`;}
function fitCanvas(){if(!state.visible.length)return;const box=$('#viewport').getBoundingClientRect(),minX=Math.min(...state.visible.map(n=>positionFor(n).x)),minY=Math.min(...state.visible.map(n=>positionFor(n).y)),maxX=Math.max(...state.visible.map(n=>positionFor(n).x+320)),maxY=Math.max(...state.visible.map(n=>positionFor(n).y+440));const scale=Math.max(.035,Math.min(.9,(box.width-70)/(maxX-minX),(box.height-85)/(maxY-minY)));state.transform={scale,x:(box.width-(maxX-minX)*scale)/2-minX*scale,y:(box.height-(maxY-minY)*scale)/2-minY*scale-9};transformWorld();}
function zoomAt(factor,x,y){const t=state.transform,scale=Math.max(.035,Math.min(1.8,t.scale*factor));t.x=x-(x-t.x)*scale/t.scale;t.y=y-(y-t.y)*scale/t.scale;t.scale=scale;transformWorld();}
function localPoint(e){const r=$('#viewport').getBoundingClientRect(),t=state.transform;return{x:(e.clientX-r.left-t.x)/t.scale,y:(e.clientY-r.top-t.y)/t.scale};}
function startNodeDrag(e,n,element){if(e.button!==0)return;e.preventDefault();e.stopPropagation();state.suppressInspector=true;selectNode(n.id);state.suppressInspector=false;document.querySelector('.inspector')?.classList.remove('is-open');state.drag={kind:'node',id:n.id,element,startX:e.clientX,startY:e.clientY,x:positionFor(n).x,y:positionFor(n).y,moved:false};}
function startConnection(e,n,port,direction){if(e.button!==0)return;e.preventDefault();e.stopPropagation();state.connecting={nodeId:n.id,port,direction,point:portPoint(n.id,port,direction)};$('#draftEdge').hidden=false;$('#draftEdge').removeAttribute('hidden');$('#selectedHint').textContent=direction==='output'?'拖动到目标节点的输入端口':'拖动到来源节点的输出端口';}
function connectPorts(a,b){const source=a.direction==='output'?a:b,target=a.direction==='input'?a:b;if(a.direction===b.direction||source.nodeId===target.nodeId)return toast('请连接不同节点的输出端口与输入端口',true);if(['audioReferences','audioPlan'].includes(target.port)&&source.port!=='audio')return toast('声音端口需要音频输出',true);if(target.port==='videoReferences'&&source.port!=='video')return toast('视频端口需要视频输出',true);if(['prompt','context'].includes(target.port)&&source.port!=='text')return toast('提示词端口需要文本输出',true);if(['references','firstFrame'].includes(target.port)&&source.port!=='image')return toast('参考图与首帧端口需要图像输出',true);if(state.graph.edges.some(e=>e.source===source.nodeId&&e.sourcePort===source.port&&e.target===target.nodeId&&e.targetPort===target.port))return toast('此连接已存在');const visits=new Set();function reaches(id){if(id===source.nodeId)return true;if(visits.has(id))return false;visits.add(id);return state.graph.edges.filter(e=>e.source===id).some(e=>reaches(e.target));}if(reaches(target.nodeId))return toast('此连接会形成循环依赖，请调整来源',true);state.graph.edges.push({id:uid(),source:source.nodeId,sourcePort:source.port,target:target.nodeId,targetPort:target.port,role:target.port==='firstFrame'?'first_frame':target.port==='references'?'reference':target.port});markDirty();renderGraph();renderInspector();toast('连接已建立，保存后参与任务编译');}
function autoLayout(){if(!state.visible.length)return;materializeLayout();const ids=new Set(state.visible.map(n=>n.id)),levels=new Map();const visiting=new Set();function level(id){if(levels.has(id))return levels.get(id);if(visiting.has(id))return 0;visiting.add(id);const parents=state.graph.edges.filter(e=>e.target===id&&ids.has(e.source));const value=parents.length?1+Math.max(...parents.map(e=>level(e.source))):0;visiting.delete(id);levels.set(id,value);return value;}const columns=new Map();state.visible.forEach(n=>{const l=level(n.id);if(!columns.has(l))columns.set(l,[]);columns.get(l).push(n);});columns.forEach((nodes,l)=>nodes.forEach((n,i)=>n.position={x:l*390,y:i*440}));markDirty();renderGraph();fitCanvas();toast('已排列当前范围节点');}
function selectNode(id,focus=false){state.selected=id;state.selectedAsset=null;state.selectedEdge=null;$$('.graph-node').forEach(e=>e.classList.toggle('selected',e.dataset.nodeId===id));$('#selectedHint').textContent=nodeBy(id)?.label||'选择节点';$('#deleteEdgeBtn').hidden=true;renderEdges();renderInspector();if(focus){const n=nodeBy(id),r=$('#viewport').getBoundingClientRect();state.transform={scale:.8,x:r.width/2-(positionFor(n).x+125)*.8,y:r.height/2-(positionFor(n).y+150)*.8};transformWorld();}}
function deleteSelection(){if(state.selectedEdge){state.graph.edges=state.graph.edges.filter(e=>e.id!==state.selectedEdge);state.selectedEdge=null;$('#deleteEdgeBtn').hidden=true;markDirty();renderGraph();renderInspector();toast('连接已删除');return;}if(state.selected){const n=nodeBy(state.selected);if(!confirm(`删除“${n.label}”及其连线？资产文件和原镜头记录仍会保留。`))return;state.graph.nodes=state.graph.nodes.filter(x=>x.id!==n.id);state.graph.edges=state.graph.edges.filter(e=>e.source!==n.id&&e.target!==n.id);state.selected=null;markDirty();renderNavigation();renderGraph();renderInspector();renderQueue();}}
function field(label,value,onchange,{textarea=false,options=null,rows=4,mono=false}={}){const wrap=el('label','',label),input=el(options?'select':textarea?'textarea':'input',mono?'monospace':'');if(options)options.forEach(o=>{const option=el('option','',typeof o==='string'?o:o.label);option.value=typeof o==='string'?o:o.value;input.append(option);});if(textarea)input.rows=rows;input.value=value??'';input.addEventListener('change',()=>onchange(input.value,input));wrap.append(input);return wrap;}
function section(label,english=''){const e=el('div','section-label',label);e.append(el('span','',english));return e;}
function button(label,cls,callback){const b=el('button',cls,label);b.type='button';b.onclick=callback;return b;}
function renderInspector(){const body=$('#inspectorBody');body.replaceChildren();const n=nodeBy(state.selected);if(state.selectedAsset){renderAssetInspector(assetBy(state.selectedAsset),body);return;}if(!n){$('#inspectorType').textContent=state.selectedEdge?'连接':'—';if(state.selectedEdge){const e=state.graph.edges.find(e=>e.id===state.selectedEdge);body.append(section('连接设置','CONNECTION'),el('p','inspector-sub',`${nodeBy(e.source)?.label} → ${nodeBy(e.target)?.label}`),field('引用用途',e.role||'reference',v=>{e.role=v;markDirty();},{options:[{value:'reference',label:'画面参考'},{value:'identity',label:'人物身份'},{value:'first_frame',label:'批准首帧'},{value:'prompt',label:'提示词'},{value:'source',label:'复用源'},{value:'media',label:'待审素材'}]}),button('删除此连接','delete-button',deleteSelection));}else{const empty=el('div','empty-inspector','↖');empty.append(el('p','','选择画布中的节点\n检查资源、依赖与生成参数'));body.append(empty);}return;}$('#inspectorType').textContent=types[n.type]?.name||n.type;body.append(el('span','eyebrow',n.shotId?`${n.shotId} / ${n.type.toUpperCase()}`:n.type.toUpperCase()),el('h2','',n.label),el('p','inspector-sub',n.shotId?shotBy(n.shotId)?.scene||'制作节点':'项目共享资源'));
const update=(key,value)=>{n.data=n.data||{};n.data[key]=value;markDirty();renderGraph();renderQueue();};body.append(field('节点名称',n.label,v=>{n.label=v;markDirty();renderGraph();}));
const status=nodeStatus(n),ready=el('div',`readiness ${status.status==='ready'||status.status==='complete'?'ready':''}`);ready.append(el('strong','',nodeStatusLabel(n,status.status)),el('p','',status.status==='external'?'此节点由 Codex 调用图像工具完成。网页保存待办与依赖，不会自行生成。':status.status==='ready'?'依赖检查通过。预演可查看实际任务参数。':state.dirty?'工作流有更改，请保存并重新检查依赖。':'生成前先检查上游资源、审核状态与模型参数。'));if(status.missing?.length){const ul=el('ul','missing-list');status.missing.forEach(m=>ul.append(el('li','',typeof m==='string'?m:JSON.stringify(m))));ready.append(ul);}body.append(ready);
if(['asset','image','video'].includes(n.type))body.append(createPreview(n,true));
if(n.type==='asset'){const a=assetBy(n.assetId);body.append(field('关联资产',n.assetId||'',v=>{n.assetId=v;markDirty();renderGraph();renderInspector();},{options:[{value:'',label:'选择资产…'},...state.assets.map(a=>({value:a.id,label:a.name}))]}));if(a){body.append(el('p','provenance',a.path||'等待导入文件'),button('编辑资产资料','secondary wide',()=>{state.selectedAsset=a.id;renderInspector();}));}}
if(n.type==='prompt'||n.type==='script')body.append(field('提示文本',n.data?.text||n.data?.prompt||'',v=>update('text',v),{textarea:true,rows:12}));
if(['image','video'].includes(n.type)){body.append(section('生成设置','GENERATION'));if(n.type==='image')body.append(field('执行方式',n.data?.provider||'minimax-design',v=>{update('provider',v);renderInspector();},{options:[{value:'minimax-design',label:'MiniMax Design'},{value:'imagegen',label:'Codex · Imagegen 待办'}]}));if(n.data?.provider!=='imagegen'){const models=state.models[n.type]||[],id=n.data?.modelId||'';const opts=[{value:'',label:'选择实时模型…'},...models.map(m=>({value:modelId(m),label:m.name||m.label||m.display_name||modelId(m)}))];if(id&&!opts.some(o=>o.value===id))opts.push({value:id,label:`${id}（目录待验证）`});body.append(field('模型',id,v=>{const m=models.find(m=>modelId(m)===v);n.data.modelId=v;n.data.params=modelDefaults(m);if(Object.hasOwn(n.data.params,'generate_audio')&&n.data.audioPlan?.generateAudio!==undefined)n.data.params.generate_audio=String(n.data.audioPlan.generateAudio);markDirty();renderGraph();renderInspector();},{options:opts}));}body.append(field('节点提示词',n.data?.prompt||'',v=>update('prompt',v),{textarea:true,rows:5}));body.append(el('span','field-help','连接的提示词节点也会参与编译；实际内容请查看任务预演。'));if(n.type==='video')body.append(field('参考模式',n.data?.referenceMode||'reference',v=>update('referenceMode',v),{options:[{value:'reference',label:'多图参考'},{value:'first-frame',label:'首帧驱动'}]}));renderModelParams(n,body,update);body.append(field('模型参数 JSON',JSON.stringify(n.data?.params||{},null,2),(v,input)=>{try{const value=JSON.parse(v);if(!value||Array.isArray(value)||typeof value!=='object')throw new Error();input.setCustomValidity('');update('params',value);}catch{input.setCustomValidity('请输入有效的 JSON 对象');input.reportValidity();toast('参数未保存：请输入有效的 JSON 对象',true);}},{textarea:true,rows:5,mono:true}));if(n.type==='video')body.append(field('输出截取秒数（可留空）',n.data?.trimSeconds||'',v=>{if(v&&(!Number.isFinite(Number(v))||Number(v)<=0))return toast('截取时长应大于 0',true);update('trimSeconds',v?Number(v):null);}));}
if(n.type==='reuse'||n.type==='edit'){body.append(section('素材处理','POST-PRODUCTION'),field('制作说明',n.data?.notes||n.data?.instructions||nodeText(n),v=>update('notes',v),{textarea:true,rows:6}));if(n.type==='reuse')body.append(field('复用源镜号',n.data?.reuseFrom||'',v=>update('reuseFrom',v)));body.append(el('span','field-help','复用与后期节点作为制作依赖，不会被当成新视频自动提交。'));}
if(n.type==='review'){body.append(field('审核结论',n.data?.reviewStatus||'candidate',v=>{n.data.approved=v==='ready';update('reviewStatus',v);},{options:[{value:'candidate',label:'待内容审核'},{value:'ready',label:'批准使用'},{value:'blocked',label:'退回修改'}]}),field('审核意见',n.data?.notes||'',v=>update('notes',v),{textarea:true,rows:5}));}
if(['image','video'].includes(n.type)&&n.data?.provider!=='imagegen')body.append(button('预演并提交此节点…','secondary wide',()=>prepareRun(n)));if(n.data?.provider==='imagegen')body.append(button('复制给 Codex 的图像待办','secondary wide',()=>copyCodexTask(n)));body.append(section('上游依赖','INPUTS'));const incoming=state.graph.edges.filter(e=>e.target===n.id);if(!incoming.length)body.append(el('p','field-help',n.type==='asset'||n.type==='prompt'?'此节点可作为工作流输入。':'尚未连入上游节点。'));incoming.forEach(e=>{const row=el('div','dependency-row');row.append(el('span','',`${portLabels[e.targetPort]||e.targetPort} · ${nodeBy(e.source)?.label||e.source}`),button('定位','',()=>selectNode(e.source,true)),button('×','',()=>{state.graph.edges=state.graph.edges.filter(x=>x.id!==e.id);window.Creator?.edgeRemoved?.(e);markDirty();renderGraph();renderInspector();}));body.append(row);});body.append(button('检查此节点依赖','secondary wide',()=>validate([n.id])),button('预演此节点任务','primary wide',()=>compile([n.id])),button('删除此节点','delete-button',deleteSelection));}
function modelId(m){return String(m.id??m.modelId??m.model_id??m.model_name??m.name??'');}
async function copyCodexTask(n){const upstream=state.graph.edges.filter(e=>e.target===n.id).map(e=>nodeBy(e.source)).filter(Boolean);const paths=upstream.map(x=>assetBy(x.assetId)?.path).filter(Boolean);const prompt=[`请处理镜序工作流节点 ${n.id}（${n.shotId||'共享资源'} / ${n.label}）。`,`执行方式：Codex Imagegen。请先读取最新工作流和依赖，按真实审核状态使用参考图。`,`提示词：${n.data?.prompt||upstream.filter(x=>x.type==='prompt').map(nodeText).join('\n')||'请按项目剧本与节点信息完善'}`,paths.length?`上游参考路径：\n${paths.join('\n')}`:'尚无实际参考路径。','生成后将真实结果导入本地资产库，并回填该节点；不要自动执行下游视频任务。'].join('\n\n');try{await navigator.clipboard.writeText(prompt);toast('已复制此节点的 Codex 制作指令');}catch{toast('剪贴板不可用，请从节点设置读取制作信息',true);}}
async function prepareRun(n){if(state.uncertainRun)return toast('上次提交状态待核实，请先查看运行结果与 Design，避免重复付费。',true);if(state.busy)return;await compile([n.id]);const result=state.compiled;if(!result)return;const tasks=(result.tasks||[]).filter(t=>t.nodeId===n.id);if(!result.ready||tasks.length!==1||tasks.some(t=>t.external||t.ready===false||t.issues?.length))return toast('此节点尚未就绪，请先处理预演中的依赖与参数缺项。',true);if(tasks.some(t=>t.status==='complete'))return toast('此节点已有结果，请先审核现有素材。',true);state.preparedRun={workspaceId:state.workspaceId,nodeIds:[n.id],requestId:uid(),revision:state.graph.revision,tasks};let dialog=$('#runDialog');if(dialog)dialog.remove();dialog=el('dialog');dialog.id='runDialog';dialog.append(el('span','eyebrow','MINIMAX DESIGN'),el('h2','','确认提交生成'),el('p','','此操作将调用当前登录的 MiniMax Design 并消耗账号积分。请核对本次任务范围。'));const task=tasks[0];const details=el('div','run-details');[['镜头',`${task.shotId||'共享'} · ${n.label}`],['数量','1 个任务'],['模型',task.modelId],['生成时长',task.params?.duration?`${task.params.duration} 秒`:'按所选图像模型'],['参考图',`${(task.imagePaths||[]).length} 张实际引用`],['模型音频引用',`${(task.referenceBindings||[]).filter(b=>(b.mediaType||assetBy(b.assetId)?.mediaType)==='audio'&&b.usage==='model_reference').length} 条`],['后期音轨',`${(task.referenceBindings||[]).filter(b=>(b.mediaType||assetBy(b.assetId)?.mediaType)==='audio'&&b.usage==='post_mix').length} 条，不发送给模型`],['输出截取',task.trimSeconds?`从第 ${task.trimStartSeconds||0} 秒起，取 ${task.trimSeconds} 秒（不减少生成费用）`:'保留完整输出']].forEach(([label,value])=>{const row=el('div','dependency-row');row.append(el('span','',label),el('strong','',value));details.append(row);});dialog.append(details,el('p','field-help','单次积分以 Design 实际结算为准。此次只提交已列出的节点，不自动运行下游。'));const actions=el('div','dialog-actions');actions.append(button('取消','secondary',()=>dialog.close()),button('确认并提交 1 个任务','primary',()=>executePreparedRun(dialog)));dialog.append(actions);document.body.append(dialog);dialog.showModal();}
async function executePreparedRun(dialog){const prepared=state.preparedRun;if(!prepared||state.busy)return;if(state.workspaceId!==prepared.workspaceId||state.dirty||state.graph.revision!==prepared.revision){dialog.close();return toast('工作流已有更改，请重新预演后提交。',true);}state.busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=true);state.uncertainRun={requestId:prepared.requestId,nodeIds:prepared.nodeIds};try{const result=await api('/api/workflow/run',{method:'POST',body:JSON.stringify({nodeIds:prepared.nodeIds,confirmed:true,requestId:prepared.requestId})});state.preparedRun=null;state.uncertainRun=null;dialog.close();state.jobs=(await api('/api/jobs')).jobs||[];state.queueTab='results';renderQueue();toast(result.jobs?.length?'生成任务已提交，请在运行结果中追踪':'请求已处理，请查看运行结果');}catch(e){dialog.close();/* A lost response never triggers a second request or a new request ID. */toast(`提交未能确认：${e.message}。请核查已有任务；本页不会自动重发。`,true);state.queueTab='results';try{state.jobs=(await api('/api/jobs')).jobs||[];renderQueue();}catch{}}finally{state.busy=false;}}
function renderModelParams(n,body,update){if(n.data?.provider==='imagegen')return;const model=(state.models[n.type]||[]).find(m=>modelId(m)===n.data?.modelId);if(!model)return;const raw=model.params||model.parameters||model.schema?.properties||{},schema=Array.isArray(raw)?Object.fromEntries(raw.map(x=>[x.name||x.key,x])):raw.properties||raw;const container=el('div','model-params');Object.entries(schema).forEach(([key,spec])=>{if(!spec||typeof spec!=='object')return;const opts=spec.options||spec.enum;if(!opts&&!['number','integer','boolean'].includes(spec.type))return;const current=n.data?.params?.[key]??spec.default??'';let options=opts?.map(x=>typeof x==='object'?{value:String(x.value??x.id),label:x.label||x.name||String(x.value)}:{value:String(x),label:String(x)});if(spec.type==='boolean')options=[{value:'true',label:'开启'},{value:'false',label:'关闭'}];const input=field(spec.label||key,current,v=>{const value=['number','integer'].includes(spec.type)?Number(v):spec.type==='boolean'?v==='true':v;if(key==='generate_audio')n.data.audioPlan={...(n.data.audioPlan||{}),generateAudio:value===true||value==='true'};update('params',{...n.data.params,[key]:value});renderInspector();},{options});container.append(input);});body.append(container);if(model.paramConstraints?.length)body.append(el('span','field-help','参数组合以实时目录与服务端预演校验为准。'));}
function modelDefaults(m){const raw=m?.params||m?.parameters||m?.schema?.properties||{};const schema=Array.isArray(raw)?Object.fromEntries(raw.map(x=>[x.name||x.key,x])):raw.properties||raw;return Object.fromEntries(Object.entries(schema).filter(([,v])=>v&&typeof v==='object'&&Object.hasOwn(v,'default')).map(([k,v])=>[k,v.default]));}
function renderAssetInspector(a,body){if(!a)return;$('#inspectorType').textContent='资产资料';body.append(el('span','eyebrow',`ASSET / ${a.id}`),el('h2','',a.name),createPreview({type:'asset',assetId:a.id,label:a.name},true));const draft={name:a.name,notes:a.notes||'',reviewStatus:a.reviewStatus||'candidate',role:a.role||'reference'};body.append(field('资产名称',draft.name,v=>draft.name=v),field('用途',draft.role,v=>draft.role=v,{options:[{value:'reference',label:'画面参考'},{value:'identity',label:'人物身份'},{value:'costume',label:'服装状态'},{value:'environment',label:'环境空间'},{value:'prop',label:'道具'},{value:'first_frame',label:'首帧'},{value:'result',label:'生成结果'},{value:'voice_identity',label:'音色身份'},{value:'dialogue_performance',label:'台词表演'},{value:'ambience',label:'环境声'},{value:'music',label:'音乐'},{value:'lip_sync_driver',label:'口型驱动'},{value:'context',label:'文字上下文'},{value:'prop_spec',label:'道具文字规范'}]}),field('审核状态',draft.reviewStatus,v=>draft.reviewStatus=v,{options:[{value:'candidate',label:'候选 · 待审核'},{value:'ready',label:'批准使用'},{value:'blocked',label:'隔离 / 禁止生成引用'},{value:'missing',label:'文件缺失'}]}),field('备注与使用限制',draft.notes,v=>draft.notes=v,{textarea:true,rows:5}),button('保存资产资料','primary wide',async()=>{try{await api(`/api/assets/${encodeURIComponent(a.id)}`,{method:'PATCH',body:JSON.stringify(draft)});state.assets=(await api('/api/assets')).assets;state.validation.clear();renderAssets();renderGraph();window.Creator?.assetsChanged?.();renderInspector();toast('资产资料已更新');}catch(e){toast(e.message,true);}}),button('添加资产节点到画布','secondary wide',()=>addNode('asset',a)),section('来源','PROVENANCE'),el('p','provenance',a.path||'文件尚未导入'),el('p','provenance',typeof a.provenance==='object'?JSON.stringify(a.provenance,null,2):a.provenance||'来源未登记'));}
function renderAssets(){const list=$('#assetList'),q=$('#assetSearch').value.toLowerCase(),kind=$('#assetFilter').value;list.replaceChildren();const assets=state.assets.filter(a=>(!q||`${a.name} ${a.id} ${a.notes||''}`.toLowerCase().includes(q))&&(!kind||a.kind===kind||(kind==='character'&&['identity','costume'].includes(a.role))||(kind==='scene'&&a.role==='environment')||(kind==='prop'&&['prop','prop_spec'].includes(a.role))));assets.forEach(a=>{const row=el('div','asset-row'),thumb=el('div','asset-thumb');const url=safeUrl(a.thumbnailUrl||a.mediaUrl);if(url&&!['text','audio','video'].includes(a.mediaType)&&!['text','audio','video'].includes(a.kind)&&!/\.(mp4|wav|mp3|webm)(?:\?|$)/i.test(url)){const img=el('img');img.src=url;img.alt=a.name;img.loading='lazy';thumb.append(img);}else thumb.textContent=a.mediaType==='text'?'≡':'▧';const info=el('div','asset-info');info.append(el('strong','',a.name),el('small','',`${kindLabels[a.kind]||a.kind||'资产'} · ${assetReviewLabel(a)}`));info.onclick=()=>{state.selectedAsset=a.id;state.selected=null;renderInspector();};row.append(thumb,info,button('＋','',()=>addNode('asset',a)));row.title=a.name;list.append(row);});if(!assets.length)list.append(el('p','panel-note','没有符合条件的资产。'));}
function addNode(type,asset=null){if(!state.graph)return;const r=$('#viewport').getBoundingClientRect(),t=state.transform;const n={id:uid(),type,label:asset?.name||types[type].name,position:{x:Math.round((r.width/2-t.x)/t.scale-125),y:Math.round((r.height/2-t.y)/t.scale-140)},data:{}};if(state.shot)n.shotId=state.shot;else if(state.scene)n.data.sceneId=state.scene;if(asset)n.assetId=asset.id;if(type==='prompt')n.data.text='';if(type==='image'||type==='video'){n.data.provider=type==='image'?'imagegen':'minimax-design';n.data.modelId='';n.data.params={};n.data.prompt='';}state.graph.nodes.push(n);markDirty();renderNavigation();renderGraph();selectNode(n.id);renderQueue();toast(`已添加${types[type].name}`);}
function scopedProduction(){return state.production.shots.filter(s=>(!state.shot||(s.shotId||s.id)===state.shot)&&(!state.scene||(s.sceneId||s.scene)===state.scene));}
function scopeNodeIds(){return state.visible.map(n=>n.id);}
function renderQueue(){const body=$('#queueBody');body.replaceChildren();['pending','results','compiled'].forEach(tab=>$(`#${tab}Tab`).classList.toggle('active',state.queueTab===tab));const pending=state.graph?state.visible.filter(n=>['image','video','reuse','edit'].includes(n.type)):[];$('#pendingCount').textContent=pending.length;$('#resultsCount').textContent=state.jobs.length;$('#compiledCount').textContent=state.compiled?.tasks?.length||0;let columns,rows=[];if(state.queueTab==='pending'){columns=['镜号','制作节点','状态','依赖 / 制作方式'];rows=pending.map(n=>({id:n.id,cells:[n.shotId||'共享',n.label,nodeStatusLabel(n,nodeStatus(n).status)||'待准备',n.type==='reuse'?'复用批准素材，不新生成':n.type==='edit'?'后期制作待办':n.data?.provider==='imagegen'?'Codex · Imagegen':nodeStatus(n).missing?.join('；')||n.data?.modelId||'模型待指定']}));}else if(state.queueTab==='results'){columns=['镜号','任务 / 结果','状态','实际产物'];rows=state.jobs.map(j=>({id:j.workflowNodeId||j.nodeId||state.graph.nodes.find(n=>n.shotId===j.shotId&&n.type==='video')?.id,cells:[j.shotId||'—',j.modelId||j.kind||j.id,statuses[j.status]||j.status,j.mediaUrl?'已保存本地素材':j.error||j.taskId||'等待结果'],job:j}));}else{columns=['镜号','编译任务','准备状态','实际参数 / 缺项'];rows=(state.compiled?.tasks||[]).map(task=>({id:task.nodeId,cells:[task.shotId||'共享',task.modelId||task.kind||'制作待办',task.ready===false||task.issues?.length?'待解决':'预演完成',task.issues?.map(issue=>typeof issue==='string'?issue:JSON.stringify(issue)).join('；')||`${(task.imagePaths||task.referencePaths||[]).length} 张引用 · ${JSON.stringify(task.params||{})}`],task}));if(state.compiled?.errors?.length){const p=el('div','queue-empty queue-error',state.compiled.errors.map(e=>typeof e==='string'?e:e.message||JSON.stringify(e)).join('；'));body.append(p);}}
if(!rows.length){body.append(el('p','queue-empty',state.queueTab==='compiled'?'选择节点或当前范围进行预演，查看实际提示词、引用路径与模型参数。预演不会提交生成。':state.queueTab==='results'?'尚无运行记录。所有结果将来自真实任务台账。':'当前范围没有待制作节点。'));return;}const table=el('table','queue-table'),thead=el('thead'),header=el('tr');columns.forEach(c=>header.append(el('th','',c)));thead.append(header);const tbody=el('tbody');rows.forEach(row=>{const tr=el('tr');row.cells.forEach((c,i)=>{const td=el('td',i===2?'status-cell':'',c);td.title=String(c);tr.append(td);});tr.onclick=()=>{if(row.id){if(!state.visible.some(n=>n.id===row.id)){const n=nodeBy(row.id),s=shotBy(n?.shotId);setScope(s?.sceneId||s?.scene||'',n?.shotId||'');}selectNode(row.id,true);}if(row.task)showCompiledTask(row.task);};tbody.append(tr);});table.append(thead,tbody);body.append(table);}
function showCompiledTask(task){const body=$('#inspectorBody');body.append(section('实际编译请求'),el('p','field-help','仅为预演，尚未提交生成。'));const prompt=field('实际提示词',task.prompt||'',()=>{},{textarea:true,rows:6});prompt.querySelector('textarea').readOnly=true;body.append(prompt);const details=el('details','advanced-params');details.append(el('summary','','引用文件与参数详情'));const paths=field('实际引用文件',(task.imagePaths||task.referencePaths||[]).join('\n'),()=>{},{textarea:true,rows:3,mono:true}),params=field('模型参数',JSON.stringify(task.params||{},null,2),()=>{},{textarea:true,rows:5,mono:true});paths.querySelector('textarea').readOnly=true;params.querySelector('textarea').readOnly=true;details.append(paths,params);body.append(details);body.scrollTop=body.scrollHeight;}
async function validate(ids=scopeNodeIds(),quiet=false){if(state.busy)return;state.busy=true;try{if(!await saveGraph(false))return;const data=await api('/api/workflow/validate',{method:'POST',body:JSON.stringify({nodeIds:ids})});(data.nodes||[]).forEach(n=>state.validation.set(n.id,n));renderGraph();renderInspector();renderQueue();if(!quiet)toast(data.valid?'依赖检查完成':'依赖检查完成，请查看缺项');return data;}catch(e){if(!quiet)toast(`检查失败：${e.message}`,true);}finally{state.busy=false;}}
async function compile(ids=scopeNodeIds()){if(state.busy)return;state.busy=true;$('#compileBtn').disabled=true;try{if(!await saveGraph(false))return;state.compiled=await api('/api/workflow/compile',{method:'POST',body:JSON.stringify({nodeIds:ids})});(state.compiled.nodes||[]).forEach(n=>state.validation.set(n.id,n));state.queueTab='compiled';renderGraph();renderInspector();renderQueue();toast(state.compiled.ready?'任务预演完成，尚未生成':'预演完成，部分依赖仍需处理');if(state.compiled.tasks?.length===1)showCompiledTask(state.compiled.tasks[0]);}catch(e){toast(`预演失败：${e.message}`,true);}finally{state.busy=false;$('#compileBtn').disabled=false;}}
function switchTab(tab){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));['scenes','assets','nodes'].forEach(t=>$(`#${t}Pane`).hidden=t!==tab);}
async function load(){try{const results=await Promise.allSettled([api('/api/workflow'),api('/api/assets'),api('/api/production'),api('/api/project'),api('/api/jobs'),api('/api/status'),api('/api/models')]);if(results[0].status==='rejected')throw results[0].reason;state.graph=results[0].value.workflow||results[0].value;state.graph.nodes.forEach(n=>{n.data=n.data||{};n.position=n.position||{x:0,y:0};});if(results[1].status==='fulfilled'){state.assets=results[1].value.assets||[];state.assetRevision=results[1].value.revision;}if(results[2].status==='fulfilled')state.production=results[2].value;if(results[3].status==='fulfilled')state.project=results[3].value;if(!state.production.shots?.length&&state.project)state.production.shots=state.project.shots.map(s=>({...s,shotId:s.id}));if(results[4].status==='fulfilled')state.jobs=results[4].value.jobs||[];if(results[5].status==='fulfilled')setConnection(results[5].value.online);else setConnection(false);if(results[6].status==='fulfilled')state.models=results[6].value;else toast('实时模型目录暂不可用，仍可编辑与检查依赖',true);state.dirty=false;state.validation.clear();state.layoutKey=null;state.viewPositions.clear();if(!state.shot&&state.project?.shots?.length)state.shot=state.project.shots[0].id;if(state.shot){const initialShot=shotBy(state.shot);if(initialShot)state.scene=initialShot.sceneId||initialShot.scene||state.scene;else state.shot='';}renderNavigation();renderAssets();renderGraph();renderQueue();updateSave();requestAnimationFrame(()=>{fitCanvas();const preferred=state.visible.find(n=>n.shotId===state.shot&&['reuse','video','edit'].includes(n.type));if(preferred)selectNode(preferred.id);});await validate(scopeNodeIds(),true);}catch(e){toast(`打开项目失败：${e.message}`,true);$('#saveState').textContent='加载失败';$('#scopeStats').textContent='无法读取工作流；请确认本地服务已更新并运行';}}
function setConnection(online){state.designOnline=online;const e=$('#connection');e.classList.toggle('offline',!online);e.replaceChildren(el('i'),document.createTextNode(online?'Design 已连接':'Design 离线'));}
document.addEventListener('pointermove',e=>{if(state.connecting){const c=state.connecting,p=localPoint(e);$('#draftEdge').setAttribute('d',c.direction==='output'?bezier(c.point,p):bezier(p,c.point));return;}const d=state.drag;if(!d)return;const dx=e.clientX-d.startX,dy=e.clientY-d.startY;if(d.kind==='node'){if(!d.moved&&Math.abs(dx)+Math.abs(dy)<=3)return;if(!d.moved)materializeLayout();const n=nodeBy(d.id);n.position={x:Math.round(d.x+dx/state.transform.scale),y:Math.round(d.y+dy/state.transform.scale)};d.element.style.left=`${positionFor(n).x}px`;d.element.style.top=`${positionFor(n).y}px`;if(Math.abs(dx)+Math.abs(dy)>3)d.moved=true;renderEdges();}else{state.transform.x=d.x+dx;state.transform.y=d.y+dy;transformWorld();}});
document.addEventListener('pointerup',e=>{if(state.connecting){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.port');if(target)connectPorts(state.connecting,{nodeId:target.dataset.nodeId,port:target.dataset.port,direction:target.dataset.direction});state.connecting=null;$('#draftEdge').setAttribute('hidden','');$('#draftEdge').setAttribute('d','');$('#selectedHint').textContent=state.selected?nodeBy(state.selected)?.label:'点击节点查看设置';}if(state.drag?.moved){state.lastDragAt=Date.now();markDirty();}state.drag=null;$('#viewport').classList.remove('panning');});
$('#viewport').onpointerdown=e=>{if(e.button!==0||e.target.closest('.graph-node,.zoom,.canvas-floating')||e.target.closest('[data-edge-id]'))return;e.preventDefault();state.drag={kind:'pan',startX:e.clientX,startY:e.clientY,x:state.transform.x,y:state.transform.y};$('#viewport').classList.add('panning');};
$('#viewport').addEventListener('wheel',e=>{e.preventDefault();const r=$('#viewport').getBoundingClientRect();zoomAt(Math.exp(-e.deltaY*.0013),e.clientX-r.left,e.clientY-r.top);},{passive:false});
$('#zoomIn').onclick=()=>{const r=$('#viewport').getBoundingClientRect();zoomAt(1.2,r.width/2,r.height/2);};$('#zoomOut').onclick=()=>{const r=$('#viewport').getBoundingClientRect();zoomAt(1/1.2,r.width/2,r.height/2);};
$('#saveBtn').onclick=()=>saveGraph();$('#fitBtn').onclick=fitCanvas;$('#layoutBtn').onclick=autoLayout;$('#allScenes').onclick=()=>setScope('');$('#shotFilter').onchange=e=>{const s=shotBy(e.target.value);setScope(s?.sceneId||s?.scene||state.scene,e.target.value);};$('#deleteEdgeBtn').onclick=deleteSelection;$('#validateBtn').onclick=()=>validate();$('#compileBtn').onclick=()=>compile();$('#emptyAdd').onclick=()=>switchTab('nodes');
['pending','results','compiled'].forEach(tab=>$(`#${tab}Tab`).onclick=()=>{state.queueTab=tab;renderQueue();});$$('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('#assetSearch').oninput=renderAssets;$('#assetFilter').onchange=renderAssets;
Object.entries(types).filter(([type])=>type!=='script').forEach(([type,info])=>{const b=el('button','catalog-button'),text=el('span');text.append(el('strong','',info.name),el('small','',info.desc));b.append(el('span','catalog-icon',info.icon),text);b.onclick=()=>addNode(type);$('#nodeCatalog').append(b);});
$('#importAssetBtn').onclick=()=>$('#importDialog').showModal();$('#cancelImport').onclick=()=>$('#importDialog').close();$('#importForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,submit=form.querySelector('[type="submit"]');submit.disabled=true;try{const payload=Object.fromEntries(new FormData(form));await api('/api/assets/import',{method:'POST',body:JSON.stringify(payload)});state.assets=(await api('/api/assets')).assets;renderAssets();renderNavigation();window.Creator?.assetsChanged?.();$('#importDialog').close();form.reset();toast('资产已导入，请审核后加入画布');}catch(error){toast(error.message,true);}finally{submit.disabled=false;}};
$('#exportBtn').onclick=()=>{const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state.graph,null,2)],{type:'application/json'}));a.download=(state.workspaceId||'studio')+'-workflow.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};$('#reloadBtn').onclick=async()=>{if(state.dirty&&!confirm('重新载入将放弃当前未保存的编辑。请先导出需要保留的草稿。'))return;$('#conflictBar').hidden=true;await load();};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(window.Creator?.saveCurrent)window.Creator.saveCurrent();else saveGraph();}if(e.key==='Escape'){state.connecting=null;$('#draftEdge').setAttribute('hidden','');}if(e.key==='Delete'&&document.body.dataset.view==='nodes'&&!e.target.closest('input,textarea,select')){e.preventDefault();deleteSelection();}});window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
setInterval(async()=>{if(document.hidden||state.busy||state.saving||state.switching||window.Creator?.mutating||!state.graph)return;const pollWorkspace=state.workspaceId;try{const [jobs,graph,assets]=await Promise.all([api('/api/jobs'),api('/api/workflow'),api('/api/assets')]);if(pollWorkspace!==state.workspaceId)return;if(assets.revision!==state.assetRevision){state.assetRevision=assets.revision;state.assets=assets.assets||[];renderAssets();renderGraph();window.Creator?.assetsChanged?.();if(!state.selectedAsset&&!document.activeElement.closest('#inspectorBody'))renderInspector();if(!state.dirty&&!state.selectedAsset&&!document.activeElement.closest('#inspectorBody'))await validate(scopeNodeIds(),true);}state.jobs=jobs.jobs||[];window.Creator?.jobsChanged?.();if(graph.revision!==state.graph?.revision){$('#conflictBar').hidden=false;if(!state.dirty)$('#saveState').textContent='有新的工作流版本';}renderQueue();}catch{/* Keep the currently open draft available while the service reconnects. */}},20000);
/* creator.js initializes the selected workspace. */



















