'use strict';
async function openPersonalLibrary(options={}){
 const dialog=el('dialog','personal-library-dialog');dialog.innerHTML='<div class="library-dialog-head"><div><small>跨项目复用 · 保存在本机</small><h2>个人资料库</h2></div><button class="secondary library-close">关闭</button></div><div class="personal-library-layout"><aside class="people-list"></aside><section><div class="library-tools"><input class="library-search" placeholder="搜索照片、声音或名称" aria-label="搜索个人资料"><button class="primary library-import">导入素材</button></div><div class="personal-library-grid"></div></section></div>';
 document.body.append(dialog);dialog.showModal();let doc,personId='',query='',showArchived=false;const aside=dialog.querySelector('.people-list'),grid=dialog.querySelector('.personal-library-grid');
 dialog.querySelector('.library-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{dialog.querySelectorAll('audio,video').forEach(p=>p.pause());dialog.remove();});
 async function refresh(){doc=await api('/api/library');draw();}
 function draw(){aside.replaceChildren(button('所有资料',personId?'secondary':'primary',()=>{personId='';draw();}));doc.people.forEach(p=>aside.append(button(p.name,personId===p.id?'primary':'quiet',()=>{personId=p.id;draw();})));aside.append(button(showArchived?'显示常用资料':'查看归档资料','quiet',()=>{showArchived=!showArchived;draw();}));if(personId)aside.append(button('重命名当前分组','quiet',async()=>{const name=prompt('新的分组名称',doc.people.find(p=>p.id===personId)?.name);if(name){await api('/api/library/people',{method:'POST',body:JSON.stringify({id:personId,name})});await refresh();}}));aside.append(button('＋ 新建人物／分组','secondary',async()=>{const name=prompt('人物或资料组名称');if(!name)return;const p=await api('/api/library/people',{method:'POST',body:JSON.stringify({name})});personId=p.id;await refresh();}));grid.replaceChildren();
  doc.assets.filter(a=>(showArchived?a.reviewStatus==='blocked':a.reviewStatus!=='blocked')&&(!personId||a.characterId===personId)&&a.name.toLowerCase().includes(query.toLowerCase())).forEach(a=>{const card=el('article','personal-card'),kind=a.mediaType;const preview=el(kind==='image'?'img':kind==='video'?'video':'audio');preview.src=safeUrl(a.mediaUrl);if(kind==='image'){preview.alt=a.name;preview.loading='lazy';}else{preview.controls=true;preview.preload='metadata';}const actions=el('div','resource-actions');const use=async(mode)=>{try{if(state.dirty&&!await saveGraph(false))return;const asset=await api('/api/library/use',{method:'POST',body:JSON.stringify({assetId:a.id})});await reloadProjectData();if(options.onSelect){dialog.close();await options.onSelect(asset);}else if(mode==='node'){dialog.close();chooseView('nodes');addNode('asset',asset);await saveGraph();}else toast('已加入当前项目资源库');}catch(e){toast(e.message,true);}};actions.append(button(options.onSelect?'选择此素材':'加入当前项目','secondary',()=>use('project')));if(!options.onSelect)actions.append(button('放到节点画布','quiet',()=>use('node')));actions.append(button('资料','quiet',()=>editEntry(a)),button(showArchived?'恢复':'归档','quiet',async()=>{await api('/api/library/assets/'+a.id,{method:'PATCH',body:JSON.stringify({reviewStatus:showArchived?'candidate':'blocked'})});await refresh();}));card.append(preview,el('h3','',a.name),el('p','field-help',(doc.people.find(p=>p.id===a.characterId)?.name||'未分组')+' · '+(kindLabels[a.role]||a.role)),actions);grid.append(card);});
  if(!grid.childElementCount)grid.append(emptyView('存放你的形象和声音','建立人物分组，导入照片、语音和视频。资料库不会自动扫描电脑或把苍头角色当作你的个人形象。'));
 }
 function editEntry(asset){const form=el('dialog','library-import-dialog');form.innerHTML='<h2>素材资料</h2><label>名称<input name="name"></label><label>所属人物<select name="characterId"></select></label><label>用途<select name="role"><option value="identity">形象照片</option><option value="voice_identity">声音参考</option><option value="dialogue_performance">台词表演</option><option value="reference">其他参考</option></select></label><label>录音原话<textarea name="spokenText" rows="3"></textarea></label><label>备注<textarea name="notes" rows="3"></textarea></label><div class="dialog-actions"><button class="secondary cancel">取消</button><button class="primary save">保存资料</button></div>';for(const key of ['name','role','spokenText','notes'])form.querySelector('[name='+key+']').value=asset[key]||'';const people=form.querySelector('[name=characterId]');people.append(new Option('未分组',''));doc.people.forEach(p=>people.append(new Option(p.name,p.id)));people.value=asset.characterId||'';form.querySelector('.cancel').onclick=()=>form.close();form.querySelector('.save').onclick=async()=>{try{const body={};for(const key of ['name','role','spokenText','notes','characterId'])body[key]=form.querySelector('[name='+key+']').value;await api('/api/library/assets/'+asset.id,{method:'PATCH',body:JSON.stringify(body)});form.close();await refresh();}catch(e){toast(e.message,true);}};document.body.append(form);form.showModal();form.addEventListener('close',()=>form.remove());}
 dialog.querySelector('.library-search').oninput=e=>{query=e.target.value;draw();};
 dialog.querySelector('.library-import').onclick=()=>{const form=el('dialog','library-import-dialog');form.innerHTML='<h2>导入个人资料</h2><label>名称<input name="name" placeholder="留空使用文件名"></label><label>用途<select name="role"><option value="identity">形象／人物照片</option><option value="voice_identity">声音参考</option><option value="reference">其他参考</option><option value="dialogue_performance">台词表演</option></select></label><label>录音原话（可选）<textarea name="spokenText" rows="3"></textarea></label><label>本机文件路径<input name="path" placeholder="也可以点击下面选择文件"></label><div class="dialog-actions"><button class="secondary cancel">取消</button><button class="primary choose">选择文件并导入</button><button class="secondary import-path">导入路径</button></div><p class="field-help upload-state"></p>';document.body.append(form);form.showModal();form.querySelector('.cancel').onclick=()=>form.close();form.addEventListener('close',()=>form.remove());
  const base=()=>({personId:personId||null,name:form.querySelector('[name=name]').value,role:form.querySelector('[name=role]').value,spokenText:form.querySelector('[name=spokenText]').value});
  async function importOne(value){form.querySelector('.upload-state').textContent='正在导入…';await api('/api/library/assets',{method:'POST',body:JSON.stringify({...base(),...value})});}
  form.querySelector('.import-path').onclick=async()=>{try{await importOne({path:form.querySelector('[name=path]').value});form.close();await refresh();}catch(e){form.querySelector('.upload-state').textContent=e.message;}};
  form.querySelector('.choose').onclick=async()=>{if(window.studioDesktop){try{const paths=await window.studioDesktop.selectMedia();for(const path of paths)await importOne({path});if(paths.length){form.close();await refresh();}}catch(e){form.querySelector('.upload-state').textContent=e.message;}return;}const picker=el('input');picker.type='file';picker.multiple=true;picker.accept='image/*,audio/*,video/*';picker.onchange=async()=>{try{for(const file of picker.files){if(file.size>64*1024**2)throw new Error('大文件请使用本机路径导入');const data=await new Promise((res,rej)=>{const reader=new FileReader();reader.onload=()=>res(reader.result.split(',')[1]);reader.onerror=rej;reader.readAsDataURL(file);});await importOne({filename:file.name,dataBase64:data});}form.close();await refresh();}catch(e){form.querySelector('.upload-state').textContent=e.message;}};picker.click();};
 };
 try{await refresh();}catch(e){grid.textContent=e.message;}
}
document.addEventListener('DOMContentLoaded',()=>{const nav=document.querySelector('.view-tabs');nav.append(button('资料库','library-entry',()=>openPersonalLibrary()));const tools=document.querySelector('.asset-tools');tools?.append(button('从个人资料库选择','secondary',()=>openPersonalLibrary({onSelect:async asset=>{chooseView('nodes');addNode('asset',asset);await saveGraph();toast('资料已加入节点，可拖动端口连接并用@引用');}})));});
