'use strict';
async function openVoiceLab(){
 if(!state.project||state.switching)return toast('请先打开项目');
 if(window.ProductionController?.isVoiceLab)return;
 if(window.ProductionController&&!window.ProductionController.close())return;
 closeReview();closeInspector();const wid=state.workspaceId,key='dingzhen.voice-lab.'+wid;
 const request=async(path,body,method)=>{const r=await fetch(path,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json','X-Studio-Request':'1','X-Studio-Workspace':wid},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error||'调试台请求失败');return d;};
 const surface=el('section','voice-lab-surface');
 surface.innerHTML=`<header class="voice-lab-heading"><div class="lab-title-group"><h1>配音</h1><span class="lab-model-status"></span></div><div class="lab-toolbar"><span class="lab-draft-status" role="status"></span><button class="quiet lab-reload-draft" title="载入已保存配置">恢复</button><button class="secondary lab-save">保存</button><button class="quiet lab-close" title="返回分镜">关闭</button></div></header>
 <div class="voice-lab-layout"><section class="lab-controls"><div class="lab-form-scroll">
 <div class="lab-preset-row"><div class="lab-person" hidden></div><label>角色<select name="profile"><option value="">自定义</option></select></label><label>试演<select name="audition"><option value="">自定义台词</option></select></label></div>
 <div class="lab-mode-row"><label>模式<select name="mode"><option value="design">设计声线 · 1.7B</option><option value="reference">固定声线 · 0.6B</option></select></label><button class="quiet lab-settings-toggle" aria-expanded="false" title="名称、种子与生成设置">参数 <span aria-hidden="true">⌄</span></button></div>
 <label data-mode="design">声线<textarea name="description" rows="3" placeholder="声线描述"></textarea></label><label data-mode="design">表演<textarea name="performance" rows="2" placeholder="本句表演"></textarea></label>
 <label data-mode="reference" hidden>参考声音<select name="reference"><option value="">选择声音</option></select></label><label data-mode="reference" hidden>参考原话<textarea name="referenceText" rows="2"></textarea></label>
 <label class="lab-script-field"><span>台词 <small class="lab-text-count">0 / 200</small></span><textarea name="text" rows="3" maxlength="200" placeholder="输入台词"></textarea></label>
 <section class="lab-advanced" hidden><div class="lab-settings"><label class="lab-name-field">名称<input name="name" maxlength="120"></label><label>种子<div class="lab-seed-row"><input name="seed" type="number" min="0" max="2147483647" value="1234"><button class="secondary lab-random" title="更换种子" aria-label="更换种子">↻</button></div></label><label>变化<select name="temperature"><option value="0.7">低 · 0.7</option><option value="0.9" selected>中 · 0.9</option><option value="1.1">高 · 1.1</option></select></label><label>设备<select name="device"></select></label></div></section>
 </div><footer class="lab-run-footer"><div class="lab-activity" hidden></div><div class="lab-generate-row"><button class="primary lab-generate" disabled><span>生成试听</span></button><kbd>Ctrl ↵</kbd></div></footer></section>
 <section class="lab-listen"><header class="lab-history-head"><div><h2>试听版本</h2><span class="lab-take-count">0</span></div><div class="lab-history-tools"><input class="lab-take-search" aria-label="搜索试听" placeholder="搜索"><select class="lab-take-filter" aria-label="筛选试听"><option value="all">全部</option><option value="active">进行中</option><option value="succeeded">已完成</option><option value="failed">失败</option></select><button class="quiet lab-refresh" title="刷新" aria-label="刷新试听">↻</button></div></header><div class="lab-takes"><div class="lab-empty"><span class="lab-spinner" aria-hidden="true"></span>载入中</div></div>
 <footer class="lab-compare-panel"><div class="lab-compare-head"><h2>A / B</h2><span class="lab-compare-note" hidden>台词不同</span><label title="试听音量">音量<input class="lab-volume" type="range" min="0" max="1" step=".05" value="1"></label></div><div class="lab-comparison"><div data-slot="A"><strong>A</strong><p>未选择</p></div><div data-slot="B"><strong>B</strong><p>未选择</p></div></div></footer></section></div>`;
 document.querySelector('.work-area').append(surface);document.body.classList.add('production-open','voice-lab-open');
 let active=true,doc=null,media=[],draftRevision=0,dirty=false,saving=false,pendingSave=false,timer=null,saveTimer=null,elapsedTimer=null,pendingRequest=null,volume=1;const slots={A:null,B:null},cards=new Map();
 const field=n=>surface.querySelector('[name='+n+']'),status=surface.querySelector('.lab-draft-status'),list=surface.querySelector('.lab-takes');
 function setStatus(message,error=false){status.textContent=message;status.title=message;status.dataset.error=String(error);}
 function draft(){const profile=doc?.profiles.find(p=>p.id===field('profile').value);const ref=field('reference').value;return {mode:field('mode').value,description:field('description').value,performance:field('mode').value==='design'?field('performance').value:'',text:field('text').value,name:field('name').value,voiceSlotId:field('profile').value,characterId:profile?.characterId||'',referenceTakeId:ref.startsWith('take:')?ref.slice(5):'',referenceAssetId:ref.startsWith('asset:')?ref.slice(6):'',referenceText:field('referenceText').value,seed:Number(field('seed').value),temperature:Number(field('temperature').value),device:field('device').value||'cuda'};}
 function retain(){localStorage.setItem(key,JSON.stringify({dirty:true,draft:draft()}));}
 function changed(){dirty=true;retain();setStatus('未保存');clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveDraft().catch(e=>setStatus(e.message,true)),800);updateGenerate();}
 async function saveDraft(){if(!doc||!dirty)return;if(saving){pendingSave=true;return;}saving=true;const sent=draft();try{const r=await request('/api/voice-lab/draft',{revision:draftRevision,draft:sent},'PUT');draftRevision=r.draftRevision;if(JSON.stringify(sent)===JSON.stringify(draft())){dirty=false;localStorage.removeItem(key);setStatus('已保存');}else pendingSave=true;}finally{saving=false;if(pendingSave){pendingSave=false;await saveDraft();}}}
 function close(){active=false;clearTimeout(timer);clearTimeout(saveTimer);clearInterval(elapsedTimer);surface.querySelectorAll('audio').forEach(a=>a.pause());if(dirty){retain();saveDraft().catch(()=>{});}surface.remove();document.body.classList.remove('production-open','voice-lab-open');window.ProductionController=null;return true;}
 window.ProductionController={isVoiceLab:true,workspace:wid,close,navigate:(page,shotId)=>{if(close())return openProduction(page,shotId);},save:()=>saveDraft().catch(e=>toast(e.message,true))};surface.querySelector('.lab-close').onclick=()=>{close();chooseView('boards');};surface.querySelector('.lab-save').onclick=()=>saveDraft().catch(e=>toast(e.message,true));
 $$('[data-production]').forEach(b=>b.classList.toggle('active',b.dataset.production==='voice-lab'));$$('.view-tabs [data-view]').forEach(b=>b.classList.remove('active'));
 const phaseLabels={queued:'排队中',loading:'加载模型',generating:'正在合成',encoding:'保存音频',complete:'已完成',failed:'失败',cancelled:'已取消'};
 function spinner(){const node=el('span','lab-spinner');node.setAttribute('aria-hidden','true');return node;}
 function phase(t){return t.progress?.phase||({queued:'queued',running:'generating',succeeded:'complete',failed:'failed',cancelled:'cancelled'})[t.status]||'queued';}
 function progressBar(t){const p=el('progress','lab-progress');p.max=100;const value=t.progress?.percent;if(t.progress?.indeterminate===false&&Number.isFinite(value))p.value=Math.max(0,Math.min(100,value));p.setAttribute('aria-label',phaseLabels[phase(t)]||'生成进度');return p;}
 function elapsed(t){const time=el('time','lab-elapsed');time.dataset.started=t.startedAt||t.createdAt;time.setAttribute('aria-label','已用时间');return time;}
 function tickElapsed(){surface.querySelectorAll('[data-started]').forEach(n=>{const start=Date.parse(n.dataset.started),sec=Math.max(0,Math.floor((Date.now()-start)/1000));n.textContent=Number.isFinite(sec)?String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0'):'00:00';});}
 async function cancelTake(t){try{await request('/api/voice-lab/cancel',{takeId:t.id});await refresh();}catch(e){toast(e.message,true);}}
 function modeChanged(){const mode=field('mode').value;surface.querySelectorAll('[data-mode]').forEach(x=>x.hidden=x.dataset.mode!==mode);const engine=doc?.engines.find(e=>e.mode===mode),previous=field('device').value;field('device').replaceChildren(...(engine?.devices||[]).map(v=>new Option(v==='cuda'?'GPU':'CPU',v)));if([...field('device').options].some(o=>o.value===previous))field('device').value=previous;const badge=surface.querySelector('.lab-model-status');badge.textContent=engine?.ready?(mode==='design'?'Qwen 1.7B':'Qwen 0.6B'):'未就绪';badge.classList.toggle('is-ready',!!engine?.ready);badge.title=engine?.ready?'本机模型':engine?.message||'模型未就绪';updateGenerate();}
 function updateGenerate(){const engine=doc?.engines.find(e=>e.mode===field('mode').value),busy=doc?.takes.filter(t=>['queued','running'].includes(t.status))||[],submitting=!!pendingRequest?.submitting,generateButton=surface.querySelector('.lab-generate');generateButton.disabled=!engine?.ready||!field('text').value.trim()||submitting||busy.length>=3;generateButton.replaceChildren();if(submitting||busy.length)generateButton.append(spinner());generateButton.append(el('span','',submitting?'提交中':busy.length>=3?'队列已满':busy.length?'加入队列':'生成试听'));generateButton.setAttribute('aria-busy',String(submitting||busy.length>0));surface.querySelector('.lab-text-count').textContent=field('text').value.length+' / 200';
  const activity=surface.querySelector('.lab-activity'),t=busy.find(t=>t.status==='running')||busy.at(-1);activity.hidden=!t&&!submitting;activity.replaceChildren();if(t){const row=el('div','lab-activity-head'),label=el('span','lab-phase-label',phaseLabels[phase(t)]);label.setAttribute('role','status');row.append(spinner(),label,elapsed(t),button('取消','quiet',()=>cancelTake(t)));activity.append(row,progressBar(t));}else if(submitting){const row=el('div','lab-activity-head');row.append(spinner(),el('span','','提交中'));activity.append(row,progressBar({status:'queued'}));}tickElapsed();}
 function references(){const selected=field('reference').value;field('reference').replaceChildren(new Option('选择声音',''));const takes=el('optgroup');takes.label='试听';for(const t of doc.takes.filter(t=>t.status==='succeeded'&&t.duration<=30.05)){const o=new Option(t.spec.name||t.spec.text.slice(0,20),'take:'+t.id);takes.append(o);}const assets=el('optgroup');assets.label='项目音频';media.filter(a=>a.mediaType==='audio'&&(a.duration||0)<=30.05).forEach(a=>assets.append(new Option(a.name,'asset:'+a.id)));field('reference').append(takes,assets);field('reference').value=selected;}
 function profileChanged(fill=true){const p=doc.profiles.find(p=>p.id===field('profile').value);field('audition').replaceChildren(new Option('自定义台词',''));const person=surface.querySelector('.lab-person');person.replaceChildren();person.hidden=!p;if(!p)return;const image=p.imageAssets?.find(a=>a.mediaUrl);if(image){const img=el('img');img.src=safeUrl(image.mediaUrl);img.alt=p.name;person.append(img);}person.title=p.name;p.auditions?.forEach((a,i)=>field('audition').append(new Option((a.shotId||'试演')+' · '+a.text.slice(0,26),String(i))));if(fill){if(field('mode').value==='reference'){field('reference').value='';field('referenceText').value='';}field('description').value=p.identityPrompt||'';field('name').value=p.name+' · 试听';if(p.auditions?.length){field('audition').value='0';auditionChanged();}}}
 function auditionChanged(){const p=doc.profiles.find(p=>p.id===field('profile').value),a=p?.auditions?.[Number(field('audition').value)];if(field('audition').value!==''&&a){field('text').value=a.text;field('performance').value=a.performancePrompt||'';}}
 function fill(d){for(const k of ['description','performance','text','name','referenceText','seed','temperature','mode'])if(d[k]!==undefined)field(k).value=d[k];field('profile').value=d.voiceSlotId||'';profileChanged(false);const preset=doc.profiles.find(p=>p.id===field('profile').value),caseIndex=preset?.auditions?.findIndex(a=>a.text===d.text)??-1;field('audition').value=caseIndex>=0?String(caseIndex):'';modeChanged();field('device').value=d.device||field('device').value;field('reference').value=d.referenceTakeId?'take:'+d.referenceTakeId:d.referenceAssetId?'asset:'+d.referenceAssetId:'';updateGenerate();}
 function audio(t){const a=el('audio');a.controls=true;a.preload='metadata';a.src=safeUrl(t.mediaUrl);a.volume=volume;a.addEventListener('play',()=>surface.querySelectorAll('audio').forEach(other=>{if(other!==a)other.pause();}));return a;}
 function compare(slot,t){slots[slot]=t;const box=surface.querySelector('[data-slot='+slot+']');box.querySelector('audio')?.pause();const heading=el('div','lab-slot-heading');heading.append(el('strong','',slot),el('p','',t.spec.name||t.spec.text.slice(0,20)),button('×','quiet',()=>{slots[slot]=null;box.querySelector('audio')?.pause();box.replaceChildren(el('strong','',slot),el('p','','未选择'));surface.querySelector('.lab-compare-note').hidden=true;}));box.replaceChildren(heading,audio(t));const note=surface.querySelector('.lab-compare-note');note.hidden=!(slots.A&&slots.B&&slots.A.spec.text!==slots.B.spec.text);note.title='A、B台词不同';}
 async function adopt(t){const dialog=el('dialog','lab-adopt-dialog');dialog.innerHTML='<h2>保存声音</h2><label>名称<input name="assetName" maxlength="120"></label><label>用途<select name="role"><option value="voice_identity">角色声线参考</option><option value="dialogue_performance">对白表演片段</option></select></label><label>保存到<select name="target"><option value="project">项目资源库</option><option value="library">个人资料库</option></select></label><label class="adopt-group" hidden>人物／分组<select name="personId"><option value="">未分组</option></select></label><div><button class="secondary cancel">取消</button><button class="primary confirm">存入资源库</button></div><p class="adopt-status"></p>';dialog.querySelector('[name=assetName]').value=t.spec.name||'配音试听';dialog.querySelector('[name=role]').value=t.spec.mode==='design'?'voice_identity':'dialogue_performance';document.body.append(dialog);dialog.showModal();dialog.querySelector('.cancel').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('[name=target]').onchange=async e=>{dialog.querySelector('.adopt-group').hidden=e.target.value!=='library';if(e.target.value==='library'){try{const lib=await request('/api/library');const select=dialog.querySelector('[name=personId]');select.replaceChildren(new Option('未分组',''),...lib.people.map(p=>new Option(p.name,p.id)));}catch(e){dialog.querySelector('.adopt-status').textContent=e.message;}}};dialog.querySelector('.confirm').onclick=async()=>{const b=dialog.querySelector('.confirm');b.disabled=true;try{await request('/api/voice-lab/adopt',{takeId:t.id,name:dialog.querySelector('[name=assetName]').value,role:dialog.querySelector('[name=role]').value,target:dialog.querySelector('[name=target]').value,personId:dialog.querySelector('[name=personId]').value||null,confirmed:true});dialog.close();const assetsDoc=await request('/api/assets');if(state.workspaceId===wid){state.assets=assetsDoc.assets||[];state.assetRevision=assetsDoc.revision;renderAssets();}media=(await request('/api/media')).assets;await refresh();toast('已存入所选资源库');}catch(e){dialog.querySelector('.adopt-status').textContent=e.message;b.disabled=false;}};}
 function applyFilter(){const q=surface.querySelector('.lab-take-search').value.trim().toLowerCase(),filter=surface.querySelector('.lab-take-filter').value;let visible=0;for(const t of doc?.takes||[]){const card=cards.get(t.id);if(!card)continue;const match=(filter==='all'||(filter==='active'?['queued','running'].includes(t.status):t.status===filter))&&((t.spec.name||'')+' '+t.spec.text).toLowerCase().includes(q);card.hidden=!match;if(match)visible++;else card.querySelector('audio')?.pause();}surface.querySelector('.lab-take-count').textContent=String(doc?.takes.length||0);list.classList.toggle('is-filtered-empty',!!doc?.takes.length&&!visible);}
 function renderTakes(){if(!doc.takes.length){list.replaceChildren(el('div','lab-empty','暂无试听'));surface.querySelector('.lab-take-count').textContent='0';return;}list.querySelector('.lab-empty')?.remove();for(const t of [...doc.takes].reverse()){let card=cards.get(t.id);const signature=JSON.stringify([t.status,phase(t),t.progress?.percent,t.adoptions,t.error]);if(card?.dataset.signature===signature)continue;if(!card){card=el('article','lab-take');cards.set(t.id,card);list.prepend(card);}card.dataset.signature=signature;card.dataset.takeId=t.id;card.dataset.state=t.status;card.replaceChildren();const head=el('header'),title=el('strong','',t.spec.name||'未命名试听');title.title=t.spec.name||'';const badge=el('span','lab-state',phaseLabels[phase(t)]);if(['queued','running'].includes(t.status))badge.prepend(spinner());head.append(title,badge);card.append(head,el('p','lab-take-text',t.spec.text));
   if(t.status==='succeeded'){card.append(audio(t));const actions=el('div','lab-take-actions'),compareActions=el('div','lab-take-compare');compareActions.append(button('A','secondary',()=>compare('A',t)),button('B','secondary',()=>compare('B',t)));compareActions.title='加入对比';actions.append(compareActions,button('固定声线','secondary',()=>{fill({...t.spec,mode:'reference',performance:'',referenceTakeId:t.id,referenceText:t.spec.text});changed();}),button('入库','primary',()=>adopt(t)));const meta=el('span','lab-meta',`${t.duration.toFixed(2)}s · ${t.spec.mode==='design'?'1.7B':'0.6B'}`);actions.append(meta);card.append(actions);if(t.adoptions?.length)card.append(el('span','lab-stored','已入库'));}
   else if(['queued','running'].includes(t.status)){card.append(progressBar(t));const footer=el('div','lab-running-footer');footer.append(elapsed(t),button('取消','quiet',()=>cancelTake(t)));card.append(footer);}
   else if(t.error){const error=el('p','lab-take-error',t.error);error.setAttribute('role','status');card.append(error);}
   const details=el('details','lab-take-details');details.append(el('summary','','参数'));if(t.spec.description)details.append(el('p','',t.spec.description));if(t.spec.performance)details.append(el('p','',t.spec.performance));details.append(el('small','',`种子 ${t.spec.seed} · 变化 ${t.spec.temperature}`),button('套用参数','secondary',()=>{fill(t.spec);changed();}));card.append(details);
  }applyFilter();tickElapsed();}
 let refreshInFlight=null,pollFailed=false;
 function scheduleRefresh(delay){clearTimeout(timer);if(active)timer=setTimeout(()=>refresh().catch(()=>{}),delay);}
 function refresh(){if(!active)return Promise.resolve();if(refreshInFlight)return refreshInFlight;clearTimeout(timer);let failed=true;
  refreshInFlight=(async()=>{try{const fresh=await request('/api/voice-lab');if(!active)return;doc={...doc,...fresh};if([...field('device').options].map(o=>o.value).join()!==(doc.engines.find(e=>e.mode===field('mode').value)?.devices||[]).join())modeChanged();references();renderTakes();updateGenerate();if(!dirty&&!saving)draftRevision=fresh.draftRevision;if(pollFailed){pollFailed=false;setStatus(dirty?'未保存':'');}failed=false;}catch(e){if(active){pollFailed=true;setStatus('连接中断 · 重试中',true);status.title=e.message;}throw e;}})().finally(()=>{refreshInFlight=null;scheduleRefresh(failed?3500:doc?.takes.some(t=>['queued','running'].includes(t.status))?1800:6000);});return refreshInFlight;}
 surface.querySelector('.lab-reload-draft').onclick=async()=>{if(saving)return toast('配置正在保存，请稍后再载入');if(dirty&&!confirm('用已保存配置替换当前编辑内容？取消会保留本机草稿。'))return;try{clearTimeout(saveTimer);const saved=await request('/api/voice-lab');draftRevision=saved.draftRevision;fill(saved.draft);dirty=false;localStorage.removeItem(key);setStatus('已恢复');}catch(e){toast(e.message,true);}};surface.querySelector('.lab-refresh').onclick=async()=>{try{media=(await request('/api/media')).assets;await refresh();}catch(e){toast(e.message,true);}};surface.querySelector('.lab-volume').oninput=e=>{volume=Number(e.target.value);surface.querySelectorAll('audio').forEach(a=>a.volume=volume);};surface.querySelector('.lab-random').onclick=()=>{field('seed').value=Math.floor(Math.random()*2147483647);changed();};field('profile').onchange=()=>{profileChanged();changed();};field('audition').onchange=()=>{auditionChanged();changed();};field('mode').onchange=()=>{modeChanged();changed();};field('reference').onchange=()=>{const ref=field('reference').value,t=doc.takes.find(t=>'take:'+t.id===ref),a=media.find(a=>'asset:'+a.id===ref);field('referenceText').value=t?.spec.text||a?.spokenText||'';changed();};surface.querySelector('.lab-controls').addEventListener('input',e=>{if(!['profile','audition','mode','reference'].includes(e.target.name))changed();});
 async function generate(){try{await saveDraft();const data=draft(),signature=JSON.stringify(data);if(!pendingRequest||pendingRequest.signature!==signature)pendingRequest={signature,id:'voice-lab-'+crypto.randomUUID()};pendingRequest.submitting=true;updateGenerate();await request('/api/voice-lab/preview',{...data,requestId:pendingRequest.id});pendingRequest=null;setStatus('');await refresh();}catch(e){if(pendingRequest)pendingRequest.submitting=false;setStatus(e.message,true);updateGenerate();}}
 surface.querySelector('.lab-take-search').oninput=applyFilter;surface.querySelector('.lab-take-filter').onchange=applyFilter;surface.querySelector('.lab-settings-toggle').onclick=()=>{const panel=surface.querySelector('.lab-advanced');panel.hidden=!panel.hidden;surface.querySelector('.lab-settings-toggle').setAttribute('aria-expanded',String(!panel.hidden));};elapsedTimer=setInterval(tickElapsed,1000);
 surface.querySelector('.lab-generate').onclick=generate;surface.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Enter'&&!surface.querySelector('.lab-generate').disabled){e.preventDefault();generate();}});
 try{const [initial,m]=await Promise.all([request('/api/voice-lab'),request('/api/media')]);if(!active)return;doc=initial;media=m.assets;draftRevision=doc.draftRevision;for(const p of doc.profiles.filter(p=>p.id!=='VO_CROWD'))field('profile').append(new Option(p.name,p.id));references();let local;try{local=JSON.parse(localStorage.getItem(key)||'null');}catch{}if(local?.dirty){fill(local.draft);dirty=true;setStatus('草稿已恢复');}else if(Object.keys(doc.draft).length)fill(doc.draft);else{field('profile').value=doc.profiles[0]?.id||'';profileChanged();modeChanged();}renderTakes();updateGenerate();scheduleRefresh(1800);}catch(e){setStatus(e.message,true);}
}
document.addEventListener('DOMContentLoaded',()=>{const anchor=document.querySelector('[data-production=audio]');const b=button('配音调试','production-entry',openVoiceLab);b.dataset.production='voice-lab';if(anchor)anchor.after(b);else document.querySelector('.view-tabs')?.append(b);});
